[package]
name = "struct-helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.struct_helpers_macro]
path = "struct-helpers-macro"
version = "0.1.0"
optional = true

[features]
default = ["derive"]
derive = ["struct_helpers_macro"]

[workspace]
members = ["struct-helpers-macro"]